import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { expect, test, type Page } from "@playwright/test";
import { playbackBarHeightPx } from "../../src/player/playback";

/**
 * Visual comparison against the supplied recording. Needs the recreation package on disk:
 *   APPLE_PAY_KIT=/path/to/apple-pay-recreation-kit npx playwright test tests/e2e/apple-pay-visual.spec.ts --project=chromium-ios-light-e2e
 * Writes side-by-side images and measured deltas to artifacts/apple-pay-visual/. The keyframes are
 * read from the package directory at test time and are never copied into the app.
 */
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const kit = process.env.APPLE_PAY_KIT ?? "";
const out = path.join(root, "artifacts/apple-pay-visual");
const recorded = { merchantLabel: "Orchid — Villa Amara", amount: "2040.00", currency: "USD", country: "US", domain: "demo-travel-photon.felix-xiong.chatgpt.site" };
const phone = { width: 402, height: 874 };
const scale = Math.min(phone.width / 512, phone.height / 1112);
const offsetY = phone.height - 1112 * scale;

type Measure = {
  top: number | null;
  left: number | null;
  right: number | null;
  card: { x: number; y: number; w: number; h: number } | null;
  spinner: { x: number; y: number } | null;
  dimRatio: number | null;
  sides: { left: number; right: number };
  boxes?: Record<string, { x: number; y: number; w: number; h: number } | null>;
};

const delta = (a: number | null | undefined, b: number | null | undefined) => (a == null || b == null ? "–" : String(+(b - a).toFixed(1)));

/** A readable summary of report.json: every keyframe's measured deltas and the stable-state boxes. */
function summarize(rows: Array<Record<string, unknown>>, phoneRows: Array<Record<string, unknown>>): string {
  const lines = [
    "# Apple Pay presentation: measured comparison with the supplied recording",
    "",
    "Generated by `tests/e2e/apple-pay-visual.spec.ts`. Both images are measured with the same pixel detectors (512 × 1112 source px).",
    "Δ = recreation − reference. Stable-bound tolerance ±3 px; phase-boundary tolerance ±1 source frame.",
    "",
    "| frame | s | sheet top ref/rec (Δ) | left Δ | right Δ | red card ref → rec | card Δx,Δy,Δw,Δh | dim ratio ref/rec | spinner Δx,Δy |",
    "| ---: | ---: | --- | ---: | ---: | --- | --- | --- | --- |",
  ];
  for (const row of rows) {
    const r = row.reference as Measure;
    const c = row.recreation as Measure;
    const card = (m: Measure) => (m.card ? `${m.card.x},${m.card.y} ${m.card.w}×${m.card.h}` : "–");
    const cardDelta = r.card && c.card ? [c.card.x - r.card.x, c.card.y - r.card.y, c.card.w - r.card.w, c.card.h - r.card.h].join(",") : "–";
    const spin = r.spinner && c.spinner ? `${(c.spinner.x - r.spinner.x).toFixed(1)},${(c.spinner.y - r.spinner.y).toFixed(1)}` : "–";
    lines.push(
      `| ${row.frame} | ${row.time} | ${r.top ?? "–"}/${c.top ?? "–"} (${delta(r.top, c.top)}) | ${delta(r.left, c.left)} | ${delta(r.right, c.right)} | ${card(r)} → ${card(c)} | ${cardDelta} | ${r.dimRatio?.toFixed(3) ?? "–"}/${c.dimRatio?.toFixed(3) ?? "–"} | ${spin} |`,
    );
  }
  lines.push("", "## Settled boxes at 3.000 s and 4.500 s (x, y, w × h; Δ as x,y,w,h)", "");
  for (const frame of [90, 135]) {
    const row = rows.find((item) => item.frame === frame);
    if (!row) continue;
    const r = (row.reference as Measure).boxes ?? {};
    const c = (row.recreation as Measure).boxes ?? {};
    lines.push(`### source frame ${frame}`, "", "| region | reference | recreation | Δ |", "| --- | --- | --- | --- |");
    for (const key of Object.keys(r)) {
      const a = r[key];
      const b = c[key];
      const text = (box: typeof a) => (box ? `${box.x},${box.y} ${box.w}×${box.h}` : "–");
      const d = a && b ? [b.x - a.x, b.y - a.y, b.w - a.w, b.h - a.h].join(",") : "–";
      lines.push(`| ${key} | ${text(a)} | ${text(b)} | ${d} |`);
    }
    lines.push("");
  }
  lines.push("## Phone viewport (402 × 874), DOM geometry converted back to source px", "", "```json", JSON.stringify(phoneRows, null, 2), "```", "");
  return `${lines.join("\n")}\n`;
}

function keyframes(): Map<number, string> {
  const dir = path.join(kit, "reference/keyframes");
  const map = new Map<number, string>();
  for (const file of readdirSync(dir)) {
    const match = /^src_(\d{3})_/.exec(file);
    if (match) map.set(Number(match[1]), path.join(dir, file));
  }
  return map;
}

/** Images are served to the page through a routed URL rather than inlined, so large sets stay cheap. */
const fileUrl = (file: string) => `/__file/${Buffer.from(file).toString("base64url")}`;

async function serveFiles(page: Page, roots: string[]) {
  await page.route("**/__file/**", (route) => {
    const file = Buffer.from(new URL(route.request().url()).pathname.replace(/^\/__file\//, ""), "base64url").toString();
    if (!roots.some((allowed) => file.startsWith(allowed + path.sep))) return route.abort();
    return route.fulfill({ path: file, contentType: "image/png" });
  });
}

/** In-page pixel analysis, shared by reference frames and captures (both 512 × 1112). */
async function measureAll(page: Page, images: Array<{ image: string; idle: string }>): Promise<Measure[]> {
  return page.evaluate(async (items) => {
    const load = (src: string) =>
      new Promise<ImageData>((resolve, reject) => {
        const image = new Image();
        image.onload = () => {
          const canvas = document.createElement("canvas");
          canvas.width = 512;
          canvas.height = 1112;
          const context = canvas.getContext("2d", { willReadFrequently: true })!;
          context.drawImage(image, 0, 0, 512, 1112);
          resolve(context.getImageData(0, 0, 512, 1112));
        };
        image.onerror = reject;
        image.src = src;
      });
    const results = [];
    for (const item of items) {
      const data = await load(item.image);
      const idle = await load(item.idle);
      const px = (d: ImageData, x: number, y: number) => {
        const i = (y * 512 + x) * 4;
        return [d.data[i], d.data[i + 1], d.data[i + 2]];
      };
      const panel = [25, 24, 27];
      const isPanel = (x: number, y: number) => {
        const p = px(data, x, y);
        return Math.abs(p[0] - panel[0]) <= 12 && Math.abs(p[1] - panel[1]) <= 12 && Math.abs(p[2] - panel[2]) <= 12;
      };
      // Panel top: first run of panel fill at x = 400, past the mini app's right edge and the top corners.
      let top: number | null = null;
      for (let y = 150; y < 1105; y += 1) {
        if ([0, 1, 2, 3, 4].every((k) => isPanel(400, y + k))) {
          top = y;
          break;
        }
      }
      let left: number | null = null;
      let right: number | null = null;
      if (top !== null && top < 900) {
        const row = Math.min(1100, top + 420);
        for (let x = 0; x < 256; x += 1) if ([0, 1, 2, 3].every((k) => isPanel(x + k, row))) { left = x; break; }
        for (let x = 511; x > 256; x -= 1) if ([0, 1, 2, 3].every((k) => isPanel(x - k, row))) { right = x + 1; break; }
      }
      // The red card: strongly red pixels inside the fan region.
      let card: Measure["card"] = null;
      let spinner: Measure["spinner"] = null;
      const sides = { left: 0, right: 0 };
      if (top !== null && top < 900) {
        const y0 = Math.max(0, top + 150);
        const y1 = Math.min(1111, top + 420);
        const rows: number[] = [];
        const cols = new Map<number, number>();
        for (let y = y0; y <= y1; y += 1) {
          let count = 0;
          for (let x = 60; x < 452; x += 1) {
            const [r, g, b] = px(data, x, y);
            if (r > 120 && r - g > 70 && r - b > 50) {
              count += 1;
              cols.set(x, (cols.get(x) ?? 0) + 1);
            }
          }
          if (count >= 12) rows.push(y);
        }
        const xs = [...cols.entries()].filter(([, count]) => count >= 12).map(([x]) => x);
        if (rows.length && xs.length) {
          const x = Math.min(...xs);
          const y = rows[0];
          card = { x, y, w: Math.max(...xs) - x + 1, h: rows[rows.length - 1] - y + 1 };
        }
        // Side strips: non-panel pixels just outside the front card's left and right edges.
        const band = (xa: number, xb: number) => {
          let count = 0;
          for (let y = top + 250; y < top + 320; y += 2) for (let x = xa; x < xb; x += 2) if (!isPanel(x, y)) count += 1;
          return count;
        };
        sides.left = band(100, 150);
        sides.right = band(362, 412);
        // Spinner: blue pixels near the bottom of the sheet.
        const blue: Array<[number, number]> = [];
        for (let y = Math.min(1111, top + 760); y < Math.min(1111, top + 840); y += 1) {
          for (let x = 200; x < 312; x += 1) {
            const [r, g, b] = px(data, x, y);
            if (b > 170 && r < 90 && g > 80 && g < 190) blue.push([x, y]);
          }
        }
        if (blue.length > 8) {
          const bx = blue.map((point) => point[0]);
          const by = blue.map((point) => point[1]);
          spinner = { x: (Math.min(...bx) + Math.max(...bx)) / 2, y: (Math.min(...by) + Math.max(...by)) / 2 };
        }
      }
      // Dimming: background luminance above the sheet relative to the idle frame.
      let lum = 0;
      let idleLum = 0;
      for (let y = 170; y < 230; y += 2) {
        for (let x = 440; x < 500; x += 2) {
          const a = px(data, x, y);
          const b = px(idle, x, y);
          lum += 0.2126 * a[0] + 0.7152 * a[1] + 0.0722 * a[2];
          idleLum += 0.2126 * b[0] + 0.7152 * b[1] + 0.0722 * b[2];
        }
      }
      // Text and control boxes, in sheet-relative windows, so font metrics can be compared separately.
      const boxes: Record<string, { x: number; y: number; w: number; h: number } | null> = {};
      if (top !== null && top <= 256) {
        const bbox = (x0: number, x1: number, dy0: number, dy1: number, match: (p: number[]) => boolean) => {
          let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
          for (let y = top + dy0; y < Math.min(1111, top + dy1); y += 1) {
            for (let x = x0; x < x1; x += 1) {
              if (!match(px(data, x, y))) continue;
              minX = Math.min(minX, x); maxX = Math.max(maxX, x); minY = Math.min(minY, y); maxY = Math.max(maxY, y);
            }
          }
          return Number.isFinite(minX) ? { x: minX, y: minY, w: maxX - minX + 1, h: maxY - minY + 1 } : null;
        };
        const white = (p: number[]) => p[0] > 200 && p[1] > 200 && p[2] > 200;
        const gray = (p: number[]) => p[0] > 100 && p[0] < 175 && Math.abs(p[0] - p[1]) < 14 && Math.abs(p[1] - p[2]) < 14;
        const near = (c: number[], t: number) => (p: number[]) => Math.abs(p[0] - c[0]) <= t && Math.abs(p[1] - c[1]) <= t && Math.abs(p[2] - c[2]) <= t;
        boxes.lockup = bbox(200, 312, 28, 66, white);
        boxes.merchant = bbox(30, 482, 100, 140, gray);
        boxes.amount = bbox(30, 482, 128, 202, white);
        boxes.closeControl = bbox(20, 100, 10, 90, near([52, 51, 55], 6));
        boxes.optionsPill = bbox(60, 452, 392, 440, near([51, 50, 54], 4));
        boxes.summaryRow = bbox(20, 492, 450, 550, near([39, 38, 41], 3));
        boxes.summaryText = bbox(100, 470, 470, 530, (p) => white(p) || gray(p));
        boxes.total = bbox(40, 472, 570, 600, gray);
        boxes.domain = bbox(40, 280, 598, 670, gray);
      }
      results.push({ top, left, right, card, spinner, dimRatio: idleLum > 0 ? lum / idleLum : null, sides, boxes });
    }
    return results;
  }, images);
}

/** Side-by-side: reference | recreation | |difference| × 3, drawn in the page and returned as PNG bytes. */
async function compose(page: Page, pairs: Array<{ label: string; reference: string; recreation: string }>, options: { columns: number; scale: number; diff: boolean }): Promise<Buffer> {
  const base64 = await page.evaluate(async ({ pairs, options }) => {
    const load = (src: string) =>
      new Promise<HTMLImageElement>((resolve, reject) => {
        const image = new Image();
        image.onload = () => resolve(image);
        image.onerror = reject;
        image.src = src;
      });
    const w = Math.round(512 * options.scale);
    const h = Math.round(1112 * options.scale);
    const panels = options.diff ? 3 : 2;
    const cellW = panels * w + (panels - 1) * 8;
    const cellH = h + 34;
    const rows = Math.ceil(pairs.length / options.columns);
    const canvas = document.createElement("canvas");
    canvas.width = options.columns * cellW + (options.columns - 1) * 24 + 24;
    canvas.height = rows * cellH + (rows - 1) * 16 + 24;
    const context = canvas.getContext("2d")!;
    context.fillStyle = "#fff";
    context.fillRect(0, 0, canvas.width, canvas.height);
    for (const [index, pair] of pairs.entries()) {
      const cx = 12 + (index % options.columns) * (cellW + 24);
      const cy = 12 + Math.floor(index / options.columns) * (cellH + 16);
      const [a, b] = await Promise.all([load(pair.reference), load(pair.recreation)]);
      context.fillStyle = "#111";
      context.font = `${Math.max(12, Math.round(18 * options.scale))}px -apple-system, sans-serif`;
      context.fillText(pair.label, cx, cy + 20);
      context.drawImage(a, cx, cy + 30, w, h);
      context.drawImage(b, cx + w + 8, cy + 30, w, h);
      if (options.diff) {
        const scratch = document.createElement("canvas");
        scratch.width = 512;
        scratch.height = 1112;
        const s = scratch.getContext("2d", { willReadFrequently: true })!;
        s.drawImage(a, 0, 0, 512, 1112);
        const da = s.getImageData(0, 0, 512, 1112);
        s.drawImage(b, 0, 0, 512, 1112);
        const db = s.getImageData(0, 0, 512, 1112);
        const out = s.createImageData(512, 1112);
        for (let i = 0; i < out.data.length; i += 4) {
          for (let c = 0; c < 3; c += 1) out.data[i + c] = Math.min(255, Math.abs(da.data[i + c] - db.data[i + c]) * 3);
          out.data[i + 3] = 255;
        }
        s.putImageData(out, 0, 0);
        context.drawImage(scratch, cx + 2 * (w + 8), cy + 30, w, h);
      }
    }
    return canvas.toDataURL("image/png").split(",")[1];
  }, { pairs, options });
  return Buffer.from(base64, "base64");
}

test("visual comparison with the supplied recording", async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== "chromium-ios-light-e2e", "captures once");
  test.skip(!kit || !existsSync(path.join(kit, "reference/keyframes")), "set APPLE_PAY_KIT to the recreation package directory");
  test.setTimeout(240_000);
  mkdirSync(out, { recursive: true });
  const frames = keyframes();
  const idle = frames.get(0)!;

  // 1. The overlay alone at 512 × 1112 over the idle recorded frame as a calibration backdrop.
  await serveFiles(page, [path.join(kit, "reference/keyframes"), testInfo.outputDir, out]);
  await page.route("**/__kit/**", (route) => route.fulfill({ path: path.join(kit, decodeURIComponent(new URL(route.request().url()).pathname.replace(/^\/__kit\//, ""))) }));
  await page.setViewportSize({ width: 512, height: 1112 });
  await page.goto(`/tests/e2e/fixtures/apple-pay-capture/index.html?bg=${encodeURIComponent(`/__kit/reference/keyframes/${path.basename(idle)}`)}`);
  await page.waitForFunction(() => window.capture?.ready === true);
  await page.evaluate((request) => window.capture!.setRequest(request), recorded);
  await page.evaluate(() => document.fonts.ready);
  const captures = new Map<number, string>();
  const rows: Array<Record<string, unknown>> = [];
  const sorted = [...frames.keys()].sort((a, b) => a - b);
  for (const n of sorted) {
    await page.evaluate((seconds) => window.capture!.setTime(seconds), n / 30);
    const file = path.join(testInfo.outputDir, `capture-${String(n).padStart(3, "0")}.png`);
    await page.locator("#frame").screenshot({ path: file, animations: "allow" });
    captures.set(n, file);
    const dom = await page.evaluate(() => {
      const box = (selector: string) => {
        const rect = document.querySelector(selector)!.getBoundingClientRect();
        return { x: rect.x, y: rect.y, w: rect.width, h: rect.height };
      };
      return { sheet: box(".pp-sheet"), front: box(".pp-front"), visible: document.querySelector("[data-photon-pay-overlay]")!.getAttribute("data-visible") };
    });
    rows.push({ frame: n, time: +(n / 30).toFixed(3), dom });
  }
  for (const [index, n] of sorted.entries()) {
    const [reference, recreation] = await measureAll(page, [{ image: fileUrl(frames.get(n)!), idle: fileUrl(idle) }, { image: fileUrl(captures.get(n)!), idle: fileUrl(idle) }]);
    rows[index].reference = reference;
    rows[index].recreation = recreation;
  }

  writeFileSync(path.join(out, "capture-512-3.000s.png"), readFileSync(captures.get(90)!));
  writeFileSync(path.join(out, "capture-512-4.500s.png"), readFileSync(captures.get(135)!));
  await page.goto("/tests/e2e/fixtures/apple-pay-capture/index.html");
  for (const [n, name] of [[90, "3.000s"], [135, "4.500s"]] as const) {
    const png = await compose(page, [{ label: `source frame ${n} (${name})  |  recreation 512 × 1112  |  |difference| × 3`, reference: fileUrl(frames.get(n)!), recreation: fileUrl(captures.get(n)!) }], { columns: 1, scale: 1, diff: true });
    writeFileSync(path.join(out, `compare-${name}.png`), png);
  }
  const boundaries = [67, 70, 75, 84, 101, 110, 121, 122, 182, 185, 186, 188, 190, 198, 300, 301, 304, 314, 331, 332, 352, 353, 375, 376, 378, 388].filter((n) => frames.has(n));
  const transitions = await compose(
    page,
    boundaries.map((n) => ({ label: `frame ${n} (${(n / 30).toFixed(3)} s): reference | recreation`, reference: fileUrl(frames.get(n)!), recreation: fileUrl(captures.get(n)!) })),
    { columns: 5, scale: 0.4, diff: false },
  );
  writeFileSync(path.join(out, "compare-transitions.png"), transitions);

  // 2. The same presentation at the renderer's actual iOS phone viewport, opened from the checkout test double.
  const flow = {
    id: "visual-phone",
    title: "Visual phone",
    platform: "ios",
    theme: "light",
    contact: { name: "Airial Travel", initials: "AT" },
    nowMs: 1790008860000,
    draft: "",
    typing: false,
    screen: "conversation",
    messages: [
      { id: "in-1", text: "Villa Amara, Ubud · $2,040 total", direction: "incoming", atMs: 1790008740000 },
      { id: "checkout", text: "Villa checkout", direction: "incoming", atMs: 1790008741000, kind: "app-card", appCard: { url: "http://127.0.0.1:4174/hotel", live: true, app: "checkout" } },
    ],
  };
  await page.addInitScript((payload) => {
    if (location.origin === "http://127.0.0.1:4173") sessionStorage.setItem("imessage-demo-inline", JSON.stringify(payload));
  }, flow);
  await page.setViewportSize({ width: phone.width, height: phone.height + playbackBarHeightPx });
  await page.goto(`/?flow=visual-phone&t=1500`);
  const shell = page.locator('[data-slot="ios-messages-app"]');
  await expect(page.locator('[data-slot="app-card"]')).toHaveAttribute("data-load-count", "1");
  await page.frameLocator('[data-slot="app-card"] iframe').locator("#applepay").click();
  await expect(page.locator("[data-photon-pay-overlay]")).toHaveAttribute("data-visible", "true");
  const phoneRows: Array<Record<string, unknown>> = [];
  for (const [n, name] of [[90, "3.000s"], [135, "4.500s"]] as const) {
    await page.evaluate((seconds) => window.__photonPay!.setTime(seconds), n / 30);
    await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))));
    const file = path.join(out, `phone-${name}.png`);
    await shell.screenshot({ path: file, animations: "allow" });
    const box = (await shell.boundingBox())!;
    const dom = await page.evaluate(({ shellX, shellY }) => {
      const rect = (selector: string) => {
        const r = document.querySelector(selector)!.getBoundingClientRect();
        return { x: r.x - shellX, y: r.y - shellY, w: r.width, h: r.height };
      };
      return { sheet: rect(".pp-sheet"), front: rect(".pp-front"), overlay: rect("[data-photon-pay-overlay]") };
    }, { shellX: box.x, shellY: box.y });
    const toSource = (r: { x: number; y: number; w: number; h: number }) => ({ x: r.x / scale, y: (r.y - offsetY) / scale, w: r.w / scale, h: r.h / scale });
    phoneRows.push({ frame: n, overlayPx: dom.overlay, sheetInSource: toSource(dom.sheet), frontInSource: toSource(dom.front) });
    const png = await page.evaluate(async ({ reference, capture, label, width, height, offset }) => {
      const load = (src: string) =>
        new Promise<HTMLImageElement>((resolve) => {
          const image = new Image();
          image.onload = () => resolve(image);
          image.src = src;
        });
      const [a, b] = await Promise.all([load(reference), load(capture)]);
      const canvas = document.createElement("canvas");
      canvas.width = width * 2 + 32;
      canvas.height = height + 48;
      const context = canvas.getContext("2d")!;
      context.fillStyle = "#fff";
      context.fillRect(0, 0, canvas.width, canvas.height);
      context.fillStyle = "#111";
      context.font = "14px -apple-system, sans-serif";
      context.fillText(label, 12, 24);
      context.drawImage(a, 12, 36 + offset, width, height - offset);
      context.drawImage(b, width + 20, 36, width, height);
      return canvas.toDataURL("image/png").split(",")[1];
    }, { reference: fileUrl(frames.get(n)!), capture: fileUrl(file), label: `source frame ${n} scaled to the phone | renderer phone viewport 402 × 874 (${name})`, width: phone.width, height: phone.height, offset: offsetY });
    writeFileSync(path.join(out, `compare-phone-${name}.png`), Buffer.from(png, "base64"));
  }
  await page.keyboard.press("Escape");

  writeFileSync(path.join(out, "report.json"), `${JSON.stringify({ kit, scale, offsetY, frames: rows, phone: phoneRows }, null, 2)}\n`);
  writeFileSync(path.join(out, "report.md"), summarize(rows, phoneRows));
});
